u = input("Enter username: ")
p = input("Enter password: ")
u = u.lower().replace(" ", "_")
l = len(p)
print("Username:", u)
print("Password length:", l)
print("Length >= 8:", l >= 8)
print("Username == admin:", u == "admin")
print("Password == 1234:", p == "1234")
print("Default account:", u == "admin" and p == "123https://www.onlinegdb.com/online_c++_compiler#editor_14")
print(f"Welcome {u}\n password length = {l}")
